// components/header.tsx
'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import Hamburger from '@/components/hamburger'
import styles from './header.module.css'

const NAV_LINKS = [
  { label: 'About', href: '/#about' },
  { label: 'Projects', href: '/#projects' },
  { label: 'Skills', href: '/#skills' },
  { label: 'Experience', href: '/#experience' },
  { label: 'Resume', href: '/resume' },
  { label: 'Contact', href: '/#contact' },
]

export default function Header() {
  const [isOpenMobileMenu, setIsOpenMobileMenu] = useState(false)
  const [isScrolled, setIsScrolled] = useState(false)

  useEffect(() => {
    document.body.style.overflow = isOpenMobileMenu ? 'hidden' : ''
  }, [isOpenMobileMenu])

  useEffect(() => {
    const onScroll = () => setIsScrolled(window.scrollY > 24)
    onScroll()
    window.addEventListener('scroll', onScroll, { passive: true })
    return () => window.removeEventListener('scroll', onScroll)
  }, [])

  return (
    <>
      <header className={`${styles.headerArea} ${isScrolled ? styles.headerScrolled : ''}`}>
        <div className="container flex items-center justify-between">
          <Link href="/" className={styles.logo}>
            AM<span>.</span>dev
          </Link>

          <nav className="hidden md:block">
            <ul className="m-0 p-0 flex gap-x-8 list-none">
              {NAV_LINKS.map((link) => (
                <li key={link.href} className="inline-block">
                  <Link href={link.href} className={styles.navLink}>
                    {link.label}
                  </Link>
                </li>
              ))}
            </ul>
          </nav>

          <div className="flex items-center gap-5">
            <div className="hidden md:block">
              <a href="mailto:mohaimen707@gmail.com" className="btn-solid" style={{ padding: '11px 20px' }}>
                Let&apos;s Work
              </a>
            </div>
            <Hamburger
              checked={isOpenMobileMenu}
              onChange={setIsOpenMobileMenu}
              className="block md:hidden"
            />
          </div>
        </div>
      </header>

      <div
        className={`mobile_menu_container block md:hidden transition-transform duration-500 ease-in-out ${
          isOpenMobileMenu ? 'translate-x-0' : 'translate-x-full pointer-events-none'
        }`}
      >
        <ul className="mobile_menu">
          {NAV_LINKS.map((link) => (
            <li key={link.href} className="mobile_menu_list_item">
              <Link href={link.href} onClick={() => setIsOpenMobileMenu(false)}>
                {link.label}
              </Link>
            </li>
          ))}
        </ul>
      </div>
    </>
  )
}

// components/header.vue
<script setup lang="ts">
import { BriefcaseBusiness } from 'lucide-vue-next';

import {Button} from "~/components/ui/button";
const isOpenMobileMenu = ref(false)

watch(() => isOpenMobileMenu.value, (currentVale) => {
  if(currentVale) {
    stopBodyScroll()
  } else {
    allowBodyScroll()
  }
})

function stopBodyScroll() {
  document.body.style.overflow = "hidden";
}

function allowBodyScroll() {
  document.body.style.overflow = "";
}
</script>

<template>
  <header class="header-area header-absolute h-30">
    <div class="container flex items-center">
      <div class="logo mr-9">
        <a href="">
          <BriefcaseBusiness class="w-10 h-10" />
        </a>
      </div>
      <div class="hidden md:block">
        <ul class="m-0 p-0 list-none">
          <li class="inline-block">
            <a href="mailto:mohaimen707@gmail.com">mohaimen707@gmail.com</a>
          </li>
        </ul>
      </div>
      <div class="menu-bar mr-auto w-full">
        <div class="flex justify-end items-center">
          <nav class="hidden md:block">
            <ul class="m-0 p-0 flex gap-x-8 list-none">
              <li class="inline-block">
                <a href="/public">About</a>
              </li>
              <li class="inline-block">
                <a href="/public">Portfolio</a>
              </li>
              <li class="inline-block">
                <a href="">Resume</a>
              </li>
              <li class="inline-block">
                <a href="">Skill</a>
              </li>
              <li class="inline-block">
                <a href="">Contact</a>
              </li>
            </ul>
          </nav>
          <div class="ml-8">
            <Button as-child>
              <a href="mailto:mohaimen707@gmail.com" class="hire-me-btn">
                Let's Work
              </a>
            </Button>
          </div>
          <Hamburger v-model="isOpenMobileMenu" class="ml-5 block md:hidden" />
        </div>
      </div>
    </div>
  </header>
  <Transition name="slide">
    <div v-if="isOpenMobileMenu" class="mobile_menu_container block md:hidden">
      <ul class="mobile_menu">
        <li class="mobile_menu_list_item">
          <a href="/public">Services</a>
        </li>
        <li class="mobile_menu_list_item">
          <a href="/public">Work</a>
        </li>
        <li class="mobile_menu_list_item">
          <a href="/public">Resume</a>
        </li>
        <li class="mobile_menu_list_item">
          <a href="/public">Skill</a>
        </li>
        <li class="mobile_menu_list_item">
          <a href="/public">Contact</a>
        </li>
      </ul>
    </div>
  </Transition>
</template>

<style scoped>
.header-absolute {
  position: absolute;
  background-color: transparent;
  left: 0;
  top: 0;
  width: 100%;
  z-index: 99;
}

.header-area {
  padding: 40px 0 20px;
}

ul li a{
  /*font-weight: var(--tj-fw-medium);
  font-size: var(--tj-fz-btn);*/
}

.slide-enter-active {
  transition: all 0.6s ease-out;
}

.slide-leave-active {
  transition: all 0.6s ease-in-out;
}

.slide-enter-from {
  transform: translateX(-500px);
}
.slide-leave-to {
  transform: translateX(500px);
}

</style>
